/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoloRouteImport } from './routes/solo'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlusRouteImport } from './routes/plus'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinGameIdRouteImport } from './routes/join.$gameId'
import { Route as GameGameIdRouteImport } from './routes/game.$gameId'
import { Route as ApiPublicPaypalWebhookRouteImport } from './routes/api/public/paypal-webhook'

const SoloRoute = SoloRouteImport.update({
  id: '/solo',
  path: '/solo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlusRoute = PlusRouteImport.update({
  id: '/plus',
  path: '/plus',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinGameIdRoute = JoinGameIdRouteImport.update({
  id: '/join/$gameId',
  path: '/join/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaypalWebhookRoute = ApiPublicPaypalWebhookRouteImport.update({
  id: '/api/public/paypal-webhook',
  path: '/api/public/paypal-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/plus': typeof PlusRoute
  '/profile': typeof ProfileRoute
  '/solo': typeof SoloRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/join/$gameId': typeof JoinGameIdRoute
  '/api/public/paypal-webhook': typeof ApiPublicPaypalWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/plus': typeof PlusRoute
  '/profile': typeof ProfileRoute
  '/solo': typeof SoloRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/join/$gameId': typeof JoinGameIdRoute
  '/api/public/paypal-webhook': typeof ApiPublicPaypalWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/plus': typeof PlusRoute
  '/profile': typeof ProfileRoute
  '/solo': typeof SoloRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/join/$gameId': typeof JoinGameIdRoute
  '/api/public/paypal-webhook': typeof ApiPublicPaypalWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/plus'
    | '/profile'
    | '/solo'
    | '/game/$gameId'
    | '/join/$gameId'
    | '/api/public/paypal-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/plus'
    | '/profile'
    | '/solo'
    | '/game/$gameId'
    | '/join/$gameId'
    | '/api/public/paypal-webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/plus'
    | '/profile'
    | '/solo'
    | '/game/$gameId'
    | '/join/$gameId'
    | '/api/public/paypal-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  PlusRoute: typeof PlusRoute
  ProfileRoute: typeof ProfileRoute
  SoloRoute: typeof SoloRoute
  GameGameIdRoute: typeof GameGameIdRoute
  JoinGameIdRoute: typeof JoinGameIdRoute
  ApiPublicPaypalWebhookRoute: typeof ApiPublicPaypalWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solo': {
      id: '/solo'
      path: '/solo'
      fullPath: '/solo'
      preLoaderRoute: typeof SoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plus': {
      id: '/plus'
      path: '/plus'
      fullPath: '/plus'
      preLoaderRoute: typeof PlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$gameId': {
      id: '/join/$gameId'
      path: '/join/$gameId'
      fullPath: '/join/$gameId'
      preLoaderRoute: typeof JoinGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paypal-webhook': {
      id: '/api/public/paypal-webhook'
      path: '/api/public/paypal-webhook'
      fullPath: '/api/public/paypal-webhook'
      preLoaderRoute: typeof ApiPublicPaypalWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  PlusRoute: PlusRoute,
  ProfileRoute: ProfileRoute,
  SoloRoute: SoloRoute,
  GameGameIdRoute: GameGameIdRoute,
  JoinGameIdRoute: JoinGameIdRoute,
  ApiPublicPaypalWebhookRoute: ApiPublicPaypalWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
